/* ------------------------------------------------------------------
   Lista de películas del ciclo.

   Campos por película:
     id        (obligatorio) identificador único y estable. NO lo cambies
               una vez que haya puntuaciones cargadas: las notas se guardan
               por id.
     title     (obligatorio) como querés que se vea en la ruleta y la cartelera.
     year      (opcional) ayuda a encontrar la portada correcta en TMDb.
     overview  (opcional) sinopsis a mano. Si está, se usa esta y no la de TMDb.
     poster    (opcional) URL de una imagen de portada propia. Tiene prioridad.
     tmdbQuery (opcional) texto de búsqueda para TMDb cuando el título en
               español no alcanza (ej: "The Godfather").
     seen      (opcional) true si ya la vieron. También se marca sola cuando
               alguien la puntúa.

   Para agregar una: copiá un bloque, cambiá id/title y listo.
------------------------------------------------------------------ */
window.CC_MOVIES = [
  { id: "colony-zombis-coreanos", title: "Colony (zombis coreanos)" },
  { id: "suicide-club", title: "Suicide Club", year: 2001, tmdbQuery: "Suicide Circle",
    overview: "Tokio: una ola de suicidios en masa arranca con 54 colegialas tirándose a las vías y una investigación que nunca termina de cerrar." },
  { id: "el-polaquito", title: "El polaquito", year: 2003,
    overview: "Un pibe canta tangos, roba y sobrevive en la estación de Constitución. Retrato duro del under porteño." },
  { id: "madame-tutli-putli", title: "Madame Tutli-Putli", year: 2007, tmdbQuery: "Madame Tutli-Putli",
    overview: "Corto en stop-motion: una mujer sola en un tren nocturno cargado de bultos, y el viaje que se vuelve pesadilla." },
  { id: "la-naranja-mecanica", title: "La Naranja Mecánica", year: 1971, tmdbQuery: "A Clockwork Orange",
    overview: "Kubrick sobre la novela de Burgess: Alex y sus drugos, ultraviolencia y un Estado que intenta 'curar' el libre albedrío." },
  { id: "el-padrino", title: "El Padrino (1, 2 y 3)", year: 1972, tmdbQuery: "The Godfather",
    overview: "La saga de Coppola sobre los Corleone: poder, familia y la lenta condena moral de Michael." },
  { id: "reservoir-dogs", title: "Reservoir Dogs", year: 1992, tmdbQuery: "Reservoir Dogs",
    overview: "El debut de Tarantino: un robo de joyas que sale mal y un galpón donde nadie confía en nadie." },
  { id: "pluribus", title: "Pluribus" },
  { id: "el-camino", title: "El Camino", year: 2019, tmdbQuery: "El Camino: A Breaking Bad Movie",
    overview: "Secuela de Breaking Bad: Jesse Pinkman intenta escapar de todo lo que dejó atrás." },
  { id: "el-irlandes", title: "El irlandés", year: 2019, tmdbQuery: "The Irishman",
    overview: "Scorsese y De Niro: Frank Sheeran recuerda su vida como sicario y la desaparición de Jimmy Hoffa." },
  { id: "amelie", title: "Amélie", year: 2001, tmdbQuery: "Amélie",
    overview: "Una camarera tímida de Montmartre decide, en secreto, arreglar la vida de la gente que la rodea." },
  { id: "obsession", title: "Obsession" },
  { id: "apostle", title: "Apostle", year: 2018, tmdbQuery: "Apostle",
    overview: "1905: un hombre se infiltra en una isla gobernada por una secta para rescatar a su hermana. Del director de The Raid." },
  { id: "dark-water", title: "Dark Water", year: 2002, tmdbQuery: "Dark Water",
    overview: "Una madre en pleno divorcio y su hija se mudan a un edificio con una mancha de humedad que no para de crecer. De Hideo Nakata." },
  { id: "caveat", title: "Caveat", year: 2020, tmdbQuery: "Caveat",
    overview: "Aceptar cuidar a una mujer en una casa aislada, con la condición de usar un arnés encadenado a las paredes. Terror irlandés." },
  { id: "i-am-not-a-serial-killer", title: "I Am Not a Serial Killer", year: 2016, tmdbQuery: "I Am Not a Serial Killer",
    overview: "Un adolescente con diagnóstico de psicópata se obliga a portarse bien, hasta que aparece un asesino real en su pueblo." },
  { id: "butterfly-kisses", title: "Butterfly Kisses", year: 2018, tmdbQuery: "Butterfly Kisses",
    overview: "Falso documental: unas cintas encontradas sobre una leyenda urbana que se activa si la mirás fijo el tiempo suficiente." },
  { id: "loner", title: "Loner" },
  { id: "el-padre", title: "El padre", year: 2020, tmdbQuery: "The Father",
    overview: "Anthony Hopkins como un hombre con demencia; la película se desordena junto con su memoria." },
  { id: "incendies", title: "Incendies", year: 2010, tmdbQuery: "Incendies",
    overview: "Dos gemelos siguen el rastro de su madre hasta una guerra civil en Medio Oriente. De Denis Villeneuve." },
  { id: "lost-in-translation", title: "Lost in Translation", year: 2003, tmdbQuery: "Lost in Translation",
    overview: "Dos estadounidenses insomnes se encuentran en un hotel de Tokio. De Sofia Coppola." },
  { id: "la-piel-que-habito", title: "La piel que habito", year: 2011, tmdbQuery: "The Skin I Live In",
    overview: "Almodóvar: un cirujano plástico retiene a una persona en su mansión para un experimento con la piel." },
  { id: "the-handmaiden", title: "The Handmaiden", year: 2016, tmdbQuery: "The Handmaiden",
    overview: "Corea bajo ocupación japonesa: una estafa, una heredera encerrada y la criada que la ayuda a vestirse. De Park Chan-wook." },
  { id: "the-witch", title: "The Witch", year: 2015, tmdbQuery: "The Witch",
    overview: "Nueva Inglaterra, 1630: una familia puritana desterrada al borde del bosque se desintegra por la sospecha." },
  { id: "matrix", title: "Matrix", year: 1999, tmdbQuery: "The Matrix",
    overview: "Neo descubre que el mundo es una simulación y elige la pastilla roja." },
  { id: "martyrs", title: "Martyrs", year: 2008, tmdbQuery: "Martyrs",
    overview: "Terror francés extremo sobre venganza, dolor sostenido y una secta que busca ver qué hay del otro lado." },
  { id: "the-green-mile", title: "The Green Mile", year: 1999, tmdbQuery: "The Green Mile",
    overview: "Un guardia del corredor de la muerte en los años 30 conoce a un preso enorme con un don que no se explica." },
  { id: "sueno-de-libertad", title: "Sueño de libertad (Shawshank)", year: 1994, tmdbQuery: "The Shawshank Redemption",
    overview: "Andy Dufresne, condenado por un crimen que no cometió, cumple perpetua en Shawshank sin resignar la esperanza." },
  { id: "batman-nolan", title: "Batman de Nolan (trilogía)", year: 2008, tmdbQuery: "The Dark Knight",
    overview: "La trilogía de Christopher Nolan: Bruce Wayne, el Joker y una Gotham al borde del colapso." },
  { id: "la-lista-de-schindler", title: "La lista de Schindler", year: 1993, tmdbQuery: "Schindler's List",
    overview: "Un empresario alemán termina salvando a más de mil judíos empleándolos en su fábrica. De Spielberg." },
  { id: "senor-de-los-anillos", title: "El Señor de los Anillos (trilogía)", year: 2001, tmdbQuery: "The Lord of the Rings: The Fellowship of the Ring",
    overview: "La trilogía de Peter Jackson: destruir el Anillo Único antes de que Sauron recupere la Tierra Media." },
  { id: "el-bueno-el-malo-el-feo", title: "El bueno, el malo y el feo", year: 1966, tmdbQuery: "The Good, the Bad and the Ugly",
    overview: "Tres pistoleros buscan un cofre enterrado durante la Guerra Civil estadounidense. De Sergio Leone." },
  { id: "casino", title: "Casino", year: 1995, tmdbQuery: "Casino",
    overview: "Scorsese: cómo la mafia manejó Las Vegas desde adentro y cómo lo perdió todo." },
  { id: "lo-que-el-viento-se-llevo", title: "Lo que el viento se llevó", year: 1939, tmdbQuery: "Gone with the Wind",
    overview: "Scarlett O'Hara y el Sur de Estados Unidos durante y después de la Guerra Civil." },
  { id: "la-forma-del-agua", title: "La forma del agua", year: 2017, tmdbQuery: "The Shape of Water",
    overview: "Una empleada muda de un laboratorio secreto se enamora de la criatura anfibia que tienen encerrada. De Guillermo del Toro." },
  { id: "interestelar", title: "Interestelar", year: 2014, tmdbQuery: "Interstellar",
    overview: "Con la Tierra agonizando, un piloto cruza un agujero de gusano para buscarle otro hogar a la humanidad. De Nolan." },
  { id: "seven", title: "Seven", year: 1995, tmdbQuery: "Se7en",
    overview: "Dos detectives persiguen a un asesino que mata siguiendo los siete pecados capitales. De David Fincher." },
  { id: "el-mago-de-oz", title: "El mago de Oz", year: 1939, tmdbQuery: "The Wizard of Oz",
    overview: "Un tornado lleva a Dorothy a un mundo de color; para volver a casa tiene que llegar a Ciudad Esmeralda." },
  { id: "el-silencio-de-los-inocentes", title: "El silencio de los inocentes", year: 1991, tmdbQuery: "The Silence of the Lambs",
    overview: "Clarice Starling pide ayuda a Hannibal Lecter para atrapar a otro asesino en serie." },
  { id: "historia-de-un-matrimonio", title: "Historia de un matrimonio", year: 2019, tmdbQuery: "Marriage Story",
    overview: "Una pareja se separa y atraviesa un divorcio que los desgasta de a poco. De Noah Baumbach." },
  { id: "memento", title: "Memento", year: 2000, tmdbQuery: "Memento",
    overview: "Un hombre sin memoria de corto plazo investiga el asesinato de su esposa. La historia avanza hacia atrás." },
  { id: "rescatando-al-soldado-ryan", title: "Rescatando al soldado Ryan", year: 1998, tmdbQuery: "Saving Private Ryan",
    overview: "Después del desembarco en Normandía, una patrulla se interna en Francia para encontrar a un soldado y mandarlo a casa." },
  { id: "ciudad-de-dios", title: "Ciudad de Dios", year: 2002, tmdbQuery: "City of God",
    overview: "Tres décadas de crimen en una favela de Río contadas desde adentro por un pibe que quiere ser fotógrafo." },
  { id: "sicario", title: "Sicario", year: 2015, tmdbQuery: "Sicario",
    overview: "Una agente del FBI entra en un operativo turbio contra el narco en la frontera con México. De Villeneuve." },
  { id: "la-la-land", title: "La La Land", year: 2016, tmdbQuery: "La La Land",
    overview: "Un pianista de jazz y una actriz aspirante se enamoran en Los Ángeles. Musical de Damien Chazelle." },
  { id: "los-miserables", title: "Los miserables", year: 2012, tmdbQuery: "Les Misérables",
    overview: "Adaptación musical de Victor Hugo: Valjean, el inspector Javert y la Francia post-revolucionaria." },
  { id: "metropolis", title: "Metrópolis", year: 1927, tmdbQuery: "Metropolis",
    overview: "Fritz Lang, 1927: una ciudad futurista partida entre los que piensan arriba y los que trabajan abajo." },
  { id: "poltergeist", title: "Poltergeist", year: 1982, tmdbQuery: "Poltergeist",
    overview: "Una casa de suburbio y una familia acosada por presencias que se llevan a la hija menor a través del televisor." },
  { id: "el-pianista", title: "El pianista", year: 2002, tmdbQuery: "The Pianist",
    overview: "Wladyslaw Szpilman sobrevive escondido en la Varsovia ocupada por los nazis. De Roman Polanski." },
  { id: "curas-zombis-en-azul", title: "Curas zombis en azul" },
  { id: "parasite", title: "Parasite", year: 2019, tmdbQuery: "Parasite",
    overview: "Una familia pobre se infiltra, uno por uno, como personal de servicio en la casa de una familia rica. De Bong Joon-ho." },
  { id: "el-laberinto-del-fauno", title: "El laberinto del fauno", year: 2006, tmdbQuery: "Pan's Labyrinth",
    overview: "España, 1944: una nena escapa a un mundo de fauno y monstruos mientras la guerrilla resiste en el monte. De del Toro." },
  { id: "la-ventana-indiscreta", title: "La ventana indiscreta", year: 1954, tmdbQuery: "Rear Window",
    overview: "Un fotógrafo con una pierna enyesada se la pasa espiando a sus vecinos y cree haber visto un asesinato. De Hitchcock." },
  { id: "alien-saga", title: "Alien (saga)", year: 1979, tmdbQuery: "Alien",
    overview: "En el espacio nadie te oye gritar: la tripulación del Nostromo y lo que traen a bordo sin querer." },
  { id: "oldboy", title: "Oldboy", year: 2003, tmdbQuery: "Oldboy",
    overview: "Un hombre encerrado 15 años sin explicación es liberado de golpe y tiene cinco días para entender por qué. De Park Chan-wook." },
  { id: "joker", title: "Joker", year: 2019, tmdbQuery: "Joker",
    overview: "Arthur Fleck, comediante fracasado en una Gotham que lo maltrata, se vuelve símbolo del caos." },
  { id: "sinister", title: "Sinister", year: 2012, tmdbQuery: "Sinister",
    overview: "Un escritor de true crime encuentra en su nueva casa una caja con películas caseras de varios asesinatos." },
  { id: "quien-quiere-ser-millonario", title: "¿Quién quiere ser millonario?", year: 2008, tmdbQuery: "Slumdog Millionaire",
    overview: "Un pibe de los suburbios de Mumbai llega a la final del programa y lo acusan de hacer trampa; cada respuesta tiene una historia." },
  { id: "atrapame-si-puedes", title: "Atrápame si puedes", year: 2002, tmdbQuery: "Catch Me If You Can",
    overview: "Frank Abagnale falsifica cheques e identidades mientras un agente del FBI lo persigue por todo el país. De Spielberg." },
  { id: "climax", title: "Climax", year: 2018, tmdbQuery: "Climax",
    overview: "Una troupe de baile, una sangría cortada con LSD y una noche que se convierte en infierno. De Gaspar Noé." },
  { id: "insidious", title: "Insidious", year: 2010, tmdbQuery: "Insidious",
    overview: "Su hijo cae en un coma inexplicable y algo empieza a usarlo como puerta de entrada. De James Wan." },
  { id: "la-llamada", title: "La llamada" },
  { id: "el-grito", title: "El grito (Ju-on)", year: 2002, tmdbQuery: "Ju-on The Grudge",
    overview: "Una casa en Tokio quedó maldita por una furia que se contagia a cualquiera que entre." },
  { id: "pesadilla-calle-elm", title: "Pesadilla en la calle Elm", year: 1984, tmdbQuery: "A Nightmare on Elm Street",
    overview: "Freddy Krueger mata a los chicos de Elm Street mientras duermen. Si te dormís, te alcanza." },
  { id: "viernes-13", title: "Viernes 13", year: 1980, tmdbQuery: "Friday the 13th",
    overview: "Un campamento reabre en Crystal Lake años después de una tragedia y alguien empieza a matar a los monitores." },
  { id: "halloween", title: "Halloween", year: 1978, tmdbQuery: "Halloween",
    overview: "Michael Myers se escapa del psiquiátrico y vuelve a Haddonfield la noche de Halloween. De John Carpenter." },
  { id: "chainsaw-massacre", title: "La masacre de Texas", year: 1974, tmdbQuery: "The Texas Chain Saw Massacre",
    overview: "Un grupo de amigos en una camioneta se cruza con una familia caníbal en el interior de Texas." },
  { id: "scream", title: "Scream", year: 1996, tmdbQuery: "Scream",
    overview: "Un asesino con máscara acosa a una adolescente y juega con todas las reglas del cine de terror. De Wes Craven." },
  { id: "diamantes-de-sangre", title: "Diamantes de sangre", year: 2006, tmdbQuery: "Blood Diamond",
    overview: "Sierra Leona en guerra civil: un contrabandista y un pescador cruzan sus destinos por un diamante rosa enterrado." },
  { id: "apocalypto", title: "Apocalypto", year: 2006, tmdbQuery: "Apocalypto",
    overview: "En el ocaso de la civilización maya, un hombre escapa de un sacrificio para volver con su familia. De Mel Gibson." },
  { id: "high-school-musical", title: "High School Musical (1, 2 y 3)", year: 2006, tmdbQuery: "High School Musical",
    overview: "Troy y Gabriella entre el equipo de básquet, el musical del colegio y las presiones de cada grupito." },
  { id: "the-taste-of-tea", title: "The Taste of Tea", year: 2004, tmdbQuery: "The Taste of Tea",
    overview: "Una familia rural japonesa, entre lo cotidiano y lo surreal, con cada integrante en su propio mundo." },
  { id: "dune", title: "Dune", year: 2021, tmdbQuery: "Dune 2021",
    overview: "La familia Atreides toma el control del planeta del especias y cae en una trampa. De Denis Villeneuve." },
  { id: "project-hail-mary", title: "Project Hail Mary", year: 2026, tmdbQuery: "Project Hail Mary",
    overview: "Un profesor despierta solo en una nave, sin memoria, y descubre que es la última chance de salvar al Sol." },
  { id: "odisea", title: "Odisea" },
  { id: "2001-space-odyssey", title: "2001: Odisea del espacio", year: 1968, tmdbQuery: "2001: A Space Odyssey",
    overview: "Del monolito al feto estelar: Kubrick y un viaje a Júpiter con la computadora HAL 9000 a bordo." },
  { id: "marty-supreme", title: "Marty Supreme", year: 2025, tmdbQuery: "Marty Supreme" },
  { id: "backrooms", title: "Backrooms" },
  { id: "truman-show", title: "The Truman Show", year: 1998, tmdbQuery: "The Truman Show",
    overview: "Un hombre no sabe que su vida entera, desde que nació, es un reality televisado en vivo." },
  { id: "el-lobo-de-wall-street", title: "El lobo de Wall Street", year: 2013, tmdbQuery: "The Wolf of Wall Street",
    overview: "Jordan Belfort: fraude bursátil, drogas y exceso total en los 90. De Scorsese." },
  { id: "funny-games", title: "Funny Games", year: 1997, tmdbQuery: "Funny Games",
    overview: "Dos jóvenes de modales perfectos toman de rehén a una familia en su casa de veraneo y proponen una apuesta. De Haneke." },
  { id: "chronicle", title: "Chronicle", year: 2012, tmdbQuery: "Chronicle",
    overview: "Tres adolescentes ganan poderes telequinéticos después de encontrar algo enterrado, y uno se sale de control." },
  { id: "pontypool", title: "Pontypool", year: 2008, tmdbQuery: "Pontypool",
    overview: "Un locutor de radio en un pueblo de Ontario se entera de que el virus que enloquece a la gente se transmite por el idioma." },
  { id: "akira", title: "Akira", year: 1988, tmdbQuery: "Akira",
    overview: "Neo-Tokio, 2019: pandillas en moto, poderes psíquicos y un experimento militar que se descontrola." },
  { id: "los-8-mas-odiados", title: "Los 8 más odiados", year: 2015, tmdbQuery: "The Hateful Eight",
    overview: "Ocho desconocidos quedan varados en una posada durante una tormenta de nieve en Wyoming. De Tarantino." },
  { id: "killer-clowns", title: "Killer Klowns from Outer Space", year: 1988, tmdbQuery: "Killer Klowns from Outer Space",
    overview: "Payasos alienígenas aterrizan en un pueblo y empiezan a cosechar humanos dentro de algodón de azúcar. Serie B de culto." },
];
