/* ------------------------------------------------------------------
   IDs y portadas de TMDb para las 86 películas base.
   Generado automáticamente (buscando en TMDb con la API key).

   Por cada película: { id: <tmdbId>, poster: "<poster_path>" }
   - id      → sirve para portada, sinopsis y "dónde verla" (providers).
   - poster  → ruta de la portada; la URL se arma como
               https://image.tmdb.org/t/p/<tamaño><poster>

   TMDb busca SOLO por título (no por director). Si una película trae
   la portada equivocada, la forma correcta de arreglarla es pinear el
   id exacto: buscá la peli en themoviedb.org, copiá el número de la URL
   (.../movie/NUMERO-...) y ponelo acá, o `tmdbId: NUMERO` en movies.js.

   Ambiguas / a confirmar: pluribus (es serie), colony-zombis-coreanos,
   obsession, la-llamada, odisea, backrooms, loner, curas-zombis-en-azul.
------------------------------------------------------------------ */
window.CC_TMDB = {
  "colony-zombis-coreanos": { id: 1375646, poster: "/bWzwORubAQ40nvzsTZidle19Dbm.jpg" },
  "suicide-club": { id: 12720, poster: "/ksAr1ujk8rJTtMfZ8skWn98zemh.jpg" },
  "el-polaquito": { id: 92597, poster: "/oECJ0oMrB7JBNwzRmLiPGGtS3QC.jpg" },
  "madame-tutli-putli": { id: 35253, poster: "/lLEvanzHSpvbTpKpTfKuGAUOl91.jpg" },
  "la-naranja-mecanica": { id: 185, poster: "/p40pYh2EBPoyVyqw6qy2PAZkFVA.jpg" },
  "el-padrino": { id: 238, poster: "/5HlLUsmsv60cZVTzVns9ICZD6zU.jpg" },
  "reservoir-dogs": { id: 500, poster: "/hxmJqXFFnXLlvPIdCW2k3UGLCgZ.jpg" },
  "pluribus": { id: 1426176, poster: "/jWZDC1FhauBSyPuIRT0IWqTFcfN.jpg" },
  "el-camino": { id: 559969, poster: "/hoWADuvXs3Ua4AXBAiZYnppTupO.jpg" },
  "el-irlandes": { id: 398978, poster: "/sNilmIAwBbH0DmBOWBS6gWvNDex.jpg" },
  "amelie": { id: 194, poster: "/mYvUib00miJWxWkiXhy3QnrCj96.jpg" },
  "obsession": { id: 1339713, poster: "/smFdHvOE7dtKbQjqz7a4rK5Cep4.jpg" },
  "apostle": { id: 424121, poster: "/cGBTW4VWG1zl4QLndwGJobwvleq.jpg" },
  "dark-water": { id: 12205, poster: "/6Vca1ssUqmupTkc6U5FzUTiDv3b.jpg" },
  "caveat": { id: 744746, poster: "/nbug05AceVU8PMXIONDFxMRtq54.jpg" },
  "i-am-not-a-serial-killer": { id: 381034, poster: "/mfhVJQGUV3Lmun9wzdaPmBJ8s2u.jpg" },
  "butterfly-kisses": { id: 480733, poster: "/7XxXYgak0oUhYx8fc0xv6n7dvJ7.jpg" },
  "loner": { id: 1489999, poster: "/kHSIVSy9PCr6dzeSV8WKIBE6c8a.jpg" },
  "el-padre": { id: 600354, poster: "/oOYti9KmH3MP5R2rtXrRL06t8i0.jpg" },
  "incendies": { id: 46738, poster: "/rA40sUH6bHD5pAJ1jOcJFZPhlOe.jpg" },
  "lost-in-translation": { id: 153, poster: "/ybXq8xTs6VMx3hM4RDYMXaDZwcz.jpg" },
  "la-piel-que-habito": { id: 63311, poster: "/sW6pB4C674TDMhFcBXDbz7L0ppO.jpg" },
  "the-handmaiden": { id: 290098, poster: "/1CJWo3mJwNEi0RsSZyxbgVFOj8B.jpg" },
  "the-witch": { id: 274854, poster: "/7fwK5selQxZ7XVNBAPdewDjCfCp.jpg" },
  "matrix": { id: 603, poster: "/tpW2X2DvxtTHJ61iJ7zNYYrJihs.jpg" },
  "martyrs": { id: 9539, poster: "/9NtdiwKhQkUtEtV9ckzKjaYRtVX.jpg" },
  "the-green-mile": { id: 497, poster: "/aBQiJRxGRrX0mXFMjxyzWYFtEnf.jpg" },
  "sueno-de-libertad": { id: 278, poster: "/uRRTV7p6l2ivtODWJVVAMRrwTn2.jpg" },
  "batman-nolan": { id: 155, poster: "/8QDQExnfNFOtabLDKqfDQuHDsIg.jpg" },
  "la-lista-de-schindler": { id: 424, poster: "/3Ho0pXsnMxpGJWqdOi0KDNdaTkT.jpg" },
  "senor-de-los-anillos": { id: 120, poster: "/9xtH1RmAzQ0rrMBNUMXstb2s3er.jpg" },
  "el-bueno-el-malo-el-feo": { id: 429, poster: "/71HKV5F9bfm05ZZnjGmRuFpUVCo.jpg" },
  "casino": { id: 524, poster: "/7x8lsyTB0G7OrLzQ7qxt3ywQ4OY.jpg" },
  "lo-que-el-viento-se-llevo": { id: 770, poster: "/vEMSjJbenWci9TrxxtAPPtk3Mzj.jpg" },
  "la-forma-del-agua": { id: 399055, poster: "/ahsMZ2PCIVi5qGoPKjjeG3ZznjA.jpg" },
  "interestelar": { id: 157336, poster: "/d1QKiYtceF3GDtxvTFXFAqwwah9.jpg" },
  "seven": { id: 807, poster: "/uVPcVz4b2hnSGrXYLdIGRXwcivs.jpg" },
  "el-mago-de-oz": { id: 630, poster: "/ymUY2iIm8IuSYuIX1SsABgPyB48.jpg" },
  "el-silencio-de-los-inocentes": { id: 274, poster: "/8FdQQ3cUCs9goEOr1qUFaHackoJ.jpg" },
  "historia-de-un-matrimonio": { id: 492188, poster: "/opePIU8Qt1jayldYY3GzuxqSy2J.jpg" },
  "memento": { id: 77, poster: "/fKTPH2WvH8nHTXeBYBVhawtRqtR.jpg" },
  "rescatando-al-soldado-ryan": { id: 857, poster: "/dcKfD8xWf8XnS3tHVp7v331wdNT.jpg" },
  "ciudad-de-dios": { id: 598, poster: "/zYjngc6yGUO1IEuAwk0yAhg8CKh.jpg" },
  "sicario": { id: 273481, poster: "/mpFhUy0aiDPIF0lN8Xpg0DeNQSD.jpg" },
  "la-la-land": { id: 313369, poster: "/7pFsAaJmiOppVHcldBzg8JKBHwe.jpg" },
  "los-miserables": { id: 82695, poster: "/uTh8sNW6u8PqmU9CQwQVHjU7b7e.jpg" },
  "metropolis": { id: 19, poster: "/fCWd45ybxghuvaeSMcBsLFKY6PG.jpg" },
  "poltergeist": { id: 609, poster: "/b6JcwPnultjlXSVDGJhtPSAZSEY.jpg" },
  "el-pianista": { id: 423, poster: "/mxfLOWnHnSlbdraKfzRn5mqoqk7.jpg" },
  "curas-zombis-en-azul": { id: 622911, poster: "/56UvL0sR6aEYPuRToKZMd9UIXr9.jpg" },
  "parasite": { id: 496243, poster: "/4N55tgxDW0RRATyrZHbx0q9HUKv.jpg" },
  "el-laberinto-del-fauno": { id: 1417, poster: "/gWPkUFGlO7ZIiArUcWRBmvAwVjB.jpg" },
  "la-ventana-indiscreta": { id: 567, poster: "/fH1MipE8PXGg0rlI5cUdzxKnyA2.jpg" },
  "alien-saga": { id: 348, poster: "/pZ9cAe5FxexJjpCaeiETbXzz3Fs.jpg" },
  "oldboy": { id: 670, poster: "/45kRW1xgTq3QrZltL9mY9e9iYkH.jpg" },
  "joker": { id: 475557, poster: "/g9l7iLYusH82bbEbwGCJzhVkOe2.jpg" },
  "sinister": { id: 82507, poster: "/nsQTB6nIx3apZMbz9sZaEAmhJXp.jpg" },
  "quien-quiere-ser-millonario": { id: 12405, poster: "/ub7iEniSi23Ms3RcF551Sozb1MH.jpg" },
  "atrapame-si-puedes": { id: 640, poster: "/WboEhiMlCsy4l2u2BweerHCLFa.jpg" },
  "climax": { id: 507076, poster: "/oo8ZbKZaSFAOv96dokRTLJ29OAs.jpg" },
  "insidious": { id: 49018, poster: "/gIrBcrmtL2KEiydYKk8r94o1UGI.jpg" },
  "la-llamada": { id: 426338, poster: "/4JTf3ze7IipC66a9cqJtZZt19fy.jpg" },
  "el-grito": { id: 11838, poster: "/2fptCAZsBwvbSQ6QBGyqby6pwi3.jpg" },
  "pesadilla-calle-elm": { id: 377, poster: "/qDmeYxsfNA68Bn7aW8HSkAuVmWf.jpg" },
  "viernes-13": { id: 4488, poster: "/wLdUNsyeSd9OvKmM0CeXF6n13IL.jpg" },
  "halloween": { id: 948, poster: "/6bsDpDL312h6vEGPOPWoweaZWUG.jpg" },
  "chainsaw-massacre": { id: 30497, poster: "/dDuWWq9VpBK0PFCDytlBpZhV6ca.jpg" },
  "scream": { id: 4232, poster: "/pO39MWOrEmJYthKyWT79BYCVRrO.jpg" },
  "diamantes-de-sangre": { id: 1372, poster: "/dBuTvhQgbsoWEOGh50Bkf5qB58g.jpg" },
  "apocalypto": { id: 1579, poster: "/yQ4uC13IYVerbxMMXeSogSQUkOT.jpg" },
  "high-school-musical": { id: 10947, poster: "/1DGmWZjUJPeKGFRHGCA6VPFUBML.jpg" },
  "the-taste-of-tea": { id: 15318, poster: "/j4PqyrYfGFkCxuXmQ2FPD36kB0Q.jpg" },
  "dune": { id: 438631, poster: "/szcew6yyjcDvaL0isaPBk2e3nkF.jpg" },
  "project-hail-mary": { id: 687163, poster: "/7lwOTxajURKEWO6gI370NTrVdBO.jpg" },
  "odisea": { id: 1429828, poster: null },
  "2001-space-odyssey": { id: 62, poster: "/pGabanxaE2YvN4jhZuSN3oXO0mi.jpg" },
  "marty-supreme": { id: 1317288, poster: "/mijSU0Rws3tBBbhdE5udxPSaZvF.jpg" },
  "backrooms": { id: 108381, poster: "/ur2yYTVGPkEDmLdoQ1Obm2RKXuU.jpg" },
  "truman-show": { id: 37165, poster: "/8eWVXQZ6yqKfkuHhWD5RcdHnszT.jpg" },
  "el-lobo-de-wall-street": { id: 106646, poster: "/uthRoUeTtiep5HCoySlOjQSPCbJ.jpg" },
  "funny-games": { id: 10234, poster: "/xdqXXacYzPwVAS4AvZz87u23wyW.jpg" },
  "chronicle": { id: 76726, poster: "/t4xb2r36SR2sbUtOsPXdZ3lCmcJ.jpg" },
  "pontypool": { id: 23963, poster: "/4wWMvurzg1AoArX57pqsPWwhps2.jpg" },
  "akira": { id: 149, poster: "/vjPt8HYymLOkRv82x9JwVO7M2a5.jpg" },
  "los-8-mas-odiados": { id: 273248, poster: "/7DYGdFT4gtiD5BI6xyOU6v0XXvi.jpg" },
  "killer-clowns": { id: 16296, poster: "/vqQoDP43QNJaQFv0KMqilm62X3C.jpg" },
};
